# Generated by Django 3.1.7 on 2021-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=20)),
                ('your_email', models.CharField(max_length=20)),
                ('your_subject', models.CharField(max_length=20)),
                ('your_message', models.CharField(max_length=255)),
            ],
        ),
    ]
